implemented few tests for user route + added few todo tests
nowcommunity/nowdatabase pull request #398
Opened 2024-10-25 09:45 UTC by iritmaximus

2024-10-29 20:25 UTC, realtalin requested changes
sorry for pointing out grammar issues but it's going to bug me if i don't 😅

otherwise looks good!

2024-10-29 20:25 UTC, realtalin commented on backend/src/api-tests/user/create.test.ts
> +describe('Creating an user', () => {
```suggestion
describe('Creating a user', () => {
```

2024-10-29 20:25 UTC, realtalin commented on backend/src/api-tests/user/create.test.ts
> +  it.todo('is not successfull with missing data')
```suggestion
  it.todo('is not successful with missing data')
```

2024-10-29 20:25 UTC, realtalin commented on backend/src/api-tests/user/create.test.ts
> +  it.todo('is not successfull with incorrect password')
```suggestion
  it.todo('is not successful with incorrect password')
```

2024-10-29 20:25 UTC, realtalin commented on backend/src/api-tests/user/login.test.ts
> +  it('is not successfull with missing data', async () => {
```suggestion
  it('is not successful with missing data', async () => {
```

2024-10-29 20:25 UTC, realtalin commented on backend/src/api-tests/user/login.test.ts
> +  it('is not successfull with incorrect password', async () => {
```suggestion
  it('is not successful with incorrect password', async () => {
```

2024-10-30 13:35 UTC, iritmaximus commented
Done.

2024-10-30 17:28 UTC, realtalin approved these changes

2024-10-30 17:35 UTC, merged