add tests for permissions when creating reference
nowcommunity/nowdatabase pull request #408
Opened 2024-10-28 09:22 UTC by juhanikat

2024-10-28 11:39 UTC, iritmaximus approved these changes
LGTM

2024-10-28 11:44 UTC, iritmaximus requested changes
Sorry, I came up with a small fix.

2024-10-28 11:44 UTC, iritmaximus commented on backend/src/api-tests/reference/create.test.ts
> +    const { body: resultBody1, status: getReqStatus1 } = await send('reference/', 'PUT', {
Small thing, but could these resultBody1 be named by the permissions it has? For example `resultBodyNoPerm` and `resultBodyEr`.

2024-10-29 12:24 UTC, juhanikat commented
created new pull request for this: #420

2024-10-29 12:25 UTC, closed without merging