add tests for deleting reference without permissions
nowcommunity/nowdatabase pull request #409
Opened 2024-10-28 09:40 UTC by juhanikat

2024-10-28 11:42 UTC, iritmaximus requested changes

2024-10-28 11:42 UTC, iritmaximus commented on backend/src/api-tests/reference/delete.test.js
> +
This is missing a `pool.end()`. See https://github.com/nowcommunity/nowdatabase/blob/5ef2c82582e32d8166d972b5753c3a4a36bd60e6/backend/src/api-tests/reference/create.test.ts#L6-L19

2024-10-28 14:50 UTC, iritmaximus requested changes
I am very sorry about these multiple changes. The file should be `.ts`. I didn't notice it previously.

2024-10-29 12:26 UTC, juhanikat commented
Renamed :+1:

2024-10-29 21:45 UTC, iritmaximus requested changes
I seriously hate to be this person, but you didn't remove the `.js` file :D

2024-10-30 10:11 UTC, juhanikat commented
made a new pull request for this #422

2024-10-30 10:11 UTC, closed without merging